[workspace]
members = [
    "ricochet-robot-solver/ricochet_board",
    "ricochet-robot-solver/ricochet_solver",
    "ricochet-robot-solver/ricochet_environment",
    "ricochet-robot-solver/ricli",
    "ricochet-robot-solver/solution_generator",
    "ricochet_solver_py",
]
default-members = [
    "ricochet-robot-solver/ricochet_board",
    "ricochet-robot-solver/ricochet_solver",
    "ricochet-robot-solver/ricli",
]

[profile.release]
codegen-units = 1
debug = false
debug-assertions = false
incremental = false
lto = true
opt-level = 3
overflow-checks = false
panic = 'unwind'
rpath = false
