//! Gate-3 backward-machinery fixtures (Agent C): layered Python-vs-Rust
//! convergence on the committed corpus under `golden/backward/`
//! (generated by `pyref/gen_fixtures_backward.py`).
//!
//! Layers:
//!   (a) paths.jsonl.gz             exact/relaxed lengths incl. supported
//!   (b) propose.jsonl.gz           candidate lists — MULTISET comparison
//!                                  (candidate order is Python-set order and
//!                                  deliberately not reproduced, DESIGN §5.11)
//!   (c) final_components.jsonl.gz  plain + extended final components (sets)
//!   (d) decisions.jsonl.gz         replay_backward_decision vs python_labels
//!   (e) rollouts.jsonl.gz          full rollouts — per-decision record
//!                                  multisets (tie-breaks may reorder), with
//!                                  exact-order stats printed.

use std::collections::HashMap;
use std::io::Read;
use std::path::Path;

use serde_json::Value;

use rust_datagen::board::{grid_data_sha256, CompiledBoard};
use rust_datagen::subgoal::rollout::{
    parse_cell, parse_cell_opt, parse_replay_decision, parse_robot, parse_state, replay_decision,
    rollout_traced, RolloutStatus,
};
use rust_datagen::subgoal::{AStar, SubgoalEnv};

fn read_jsonl_gz(name: &str) -> Vec<Value> {
    let path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("golden/backward")
        .join(name);
    let bytes = std::fs::read(&path).unwrap_or_else(|e| panic!("read {path:?}: {e}"));
    let mut text = String::new();
    flate2::read::GzDecoder::new(&bytes[..])
        .read_to_string(&mut text)
        .unwrap_or_else(|e| panic!("gunzip {path:?}: {e}"));
    text.lines()
        .filter(|l| !l.trim().is_empty())
        .map(|l| serde_json::from_str(l).unwrap_or_else(|e| panic!("parse {path:?}: {e}")))
        .collect()
}

/// Compile (and cache) the board carried inline in a fixture line.
struct BoardCache(HashMap<String, CompiledBoard>);

impl BoardCache {
    fn new() -> Self {
        BoardCache(HashMap::new())
    }

    fn get(&mut self, line: &Value) -> &CompiledBoard {
        let b = &line["board"];
        let n = b["n"].as_u64().unwrap() as u16;
        let grid_data: Vec<String> = b["grid_data"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_str().unwrap().to_string())
            .collect();
        let weight = line["dependent_edge_weight"].as_i64().unwrap_or(2);
        let key = format!("{}_{weight}", grid_data_sha256(&grid_data));
        self.0
            .entry(key)
            .or_insert_with(|| CompiledBoard::compile(n, &grid_data, weight))
    }
}

// -- (a) path lengths ---------------------------------------------------------

#[test]
fn fixture_a_path_lengths() {
    let lines = read_jsonl_gz("paths.jsonl.gz");
    assert!(!lines.is_empty());
    let mut cache = BoardCache::new();
    let (mut n_triples, mut n_supported) = (0usize, 0usize);
    for line in &lines {
        let board = cache.get(line);
        let env = SubgoalEnv::new(board);
        let tag = line["tag"].as_str().unwrap();
        for (i, t) in line["triples"].as_array().unwrap().iter().enumerate() {
            let s = parse_cell(&t["s"]).unwrap();
            let e = parse_cell(&t["e"]).unwrap();
            let sup = parse_cell_opt(&t["sup"]).unwrap();
            let exact = t["exact"].as_i64();
            let relaxed = t["relaxed"].as_i64();
            assert_eq!(
                env.compute_exact(s, e, sup),
                exact,
                "{tag} triple {i}: exact({s:?},{e:?},{sup:?})"
            );
            assert_eq!(
                env.compute_relaxed(s, e, sup),
                relaxed,
                "{tag} triple {i}: relaxed({s:?},{e:?},{sup:?})"
            );
            n_triples += 1;
            if sup.is_some() {
                n_supported += 1;
            }
        }
    }
    println!(
        "fixture (a) PASS: {} boards, {n_triples} triples ({n_supported} supported), exact+relaxed both checked",
        lines.len()
    );
}

// -- (b) propose --------------------------------------------------------------

/// Candidate as comparable tuples: `core` = (bn, sp, helper, score) — must
/// match Python exactly as a multiset; `full` adds parent_support, whose
/// choice may legitimately diverge (documented §5.11 set-order divergence,
/// validated per element below).
type CandCore = ((u16, u16), (u16, u16), ((u16, u16), String), i64);
type CandFull = (CandCore, Option<(u16, u16)>);

fn py_cand(c: &Value) -> CandFull {
    let core = (
        parse_cell(&c["bn"]).unwrap(),
        parse_cell(&c["sp"]).unwrap(),
        (
            parse_cell(&c["helper"][0]).unwrap(),
            c["helper"][1].as_str().unwrap().to_string(),
        ),
        c["score"].as_i64().unwrap(),
    );
    (core, parse_cell_opt(&c["parent_support"]).unwrap())
}

fn rs_cand(c: &rust_datagen::subgoal::Candidate) -> CandFull {
    let core = (
        c.subgoal.bottleneck.pos,
        c.subgoal.support.pos,
        (c.subgoal.helper.pos, c.subgoal.helper.color_str().to_string()),
        c.score,
    );
    (core, c.parent_support)
}

#[test]
fn fixture_b_propose_candidate_sets() {
    let lines = read_jsonl_gz("propose.jsonl.gz");
    assert!(!lines.is_empty());
    let mut cache = BoardCache::new();
    let (mut n_ctx, mut n_cands, mut n_ps_div) = (0usize, 0usize, 0usize);
    for line in &lines {
        let board = cache.get(line);
        let env = SubgoalEnv::new(board);
        let tag = line["tag"].as_str().unwrap();
        for (ci, ctx) in line["contexts"].as_array().unwrap().iter().enumerate() {
            let goal = parse_cell(&ctx["goal"]).unwrap();
            let mover = parse_robot(&ctx["mover"]).unwrap();
            let helpers: Vec<_> = ctx["helpers"]
                .as_array()
                .unwrap()
                .iter()
                .map(|h| parse_robot(h).unwrap())
                .collect();
            let support = if ctx["support"].is_null() {
                None
            } else {
                Some(parse_robot(&ctx["support"]).unwrap())
            };
            let cands = env.propose(goal, &mover, &helpers, support.as_ref());
            assert_eq!(
                cands.len(),
                ctx["n_candidates"].as_u64().unwrap() as usize,
                "{tag} ctx {ci}: candidate count"
            );
            let py: Vec<CandFull> =
                ctx["candidates"].as_array().unwrap().iter().map(py_cand).collect();
            let rs: Vec<CandFull> = cands.iter().map(rs_cand).collect();

            // 1. Core multiset (everything except parent_support) — exact.
            let mut py_core: Vec<CandCore> = py.iter().map(|c| c.0.clone()).collect();
            let mut rs_core: Vec<CandCore> = rs.iter().map(|c| c.0.clone()).collect();
            py_core.sort();
            rs_core.sort();
            assert_eq!(py_core, rs_core, "{tag} ctx {ci}: core candidate multiset");

            // 2. Full multiset; any symmetric difference must be the
            // documented parent_support divergence: for BOTH sides the value
            // is a qualifying dependent support reached only because the
            // independent route (and the pinned support, when present)
            // failed — i.e. the set-order-sensitive tail of the resolution
            // list decided.
            let mut py_full = py.clone();
            let mut rs_full = rs.clone();
            py_full.sort();
            rs_full.sort();
            if py_full != rs_full {
                let diff = |a: &[CandFull], b: &[CandFull]| -> Vec<CandFull> {
                    let mut b_left: Vec<&CandFull> = b.iter().collect();
                    a.iter()
                        .filter(|x| {
                            if let Some(i) = b_left.iter().position(|y| *y == *x) {
                                b_left.remove(i);
                                false
                            } else {
                                true
                            }
                        })
                        .cloned()
                        .collect()
                };
                let py_only = diff(&py_full, &rs_full);
                let rs_only = diff(&rs_full, &py_full);
                assert_eq!(py_only.len(), rs_only.len(), "{tag} ctx {ci}: diff sizes");
                for (core, ps) in py_only.iter().chain(rs_only.iter()) {
                    let bn = core.0;
                    let ps = ps.unwrap_or_else(|| {
                        panic!("{tag} ctx {ci}: divergent parent_support is None for bn {bn:?}")
                    });
                    assert!(
                        env.compute_exact(bn, goal, Some(ps)).is_some(),
                        "{tag} ctx {ci}: divergent parent_support {ps:?} does not qualify"
                    );
                    assert!(
                        env.compute_exact(bn, goal, None).is_none(),
                        "{tag} ctx {ci}: independent route exists — divergence not the documented class"
                    );
                    if let Some(s) = &support {
                        assert!(
                            env.compute_exact(bn, goal, Some(s.pos)).is_none(),
                            "{tag} ctx {ci}: pinned support qualifies — divergence not the documented class"
                        );
                    }
                }
                n_ps_div += py_only.len();
            }
            n_ctx += 1;
            n_cands += cands.len();
        }
    }
    println!(
        "fixture (b) PASS: {} boards, {n_ctx} propose contexts, {n_cands} candidates; \
         core multiset exact everywhere; {n_ps_div} parent_support choices in the \
         documented set-order divergence class (validated per element)",
        lines.len()
    );
}

// -- (c) final components -----------------------------------------------------

fn fc_to_sorted(fc: &[bool], n: u16) -> Vec<(u16, u16)> {
    let mut cells: Vec<(u16, u16)> = fc
        .iter()
        .enumerate()
        .filter(|(_, &m)| m)
        .map(|(i, _)| ((i % n as usize) as u16, (i / n as usize) as u16))
        .collect();
    cells.sort();
    cells
}

#[test]
fn fixture_c_final_components() {
    let lines = read_jsonl_gz("final_components.jsonl.gz");
    assert!(!lines.is_empty());
    let mut cache = BoardCache::new();
    let (mut n_plain, mut n_ext) = (0usize, 0usize);
    for line in &lines {
        let board = cache.get(line);
        let n = board.n();
        let env = SubgoalEnv::new(board);
        let tag = line["tag"].as_str().unwrap();
        for row in line["goals"].as_array().unwrap() {
            let goal = parse_cell(&row["goal"]).unwrap();
            let mut expect: Vec<(u16, u16)> = row["fc"]
                .as_array()
                .unwrap()
                .iter()
                .map(|c| parse_cell(c).unwrap())
                .collect();
            expect.sort();
            let got = fc_to_sorted(&env.final_component(goal), n);
            assert_eq!(got, expect, "{tag}: final component of {goal:?}");
            n_plain += 1;
        }
        for row in line["extended"].as_array().unwrap() {
            let bn = parse_cell(&row["bn"]).unwrap();
            let sup = parse_cell(&row["sup"]).unwrap();
            let mut expect: Vec<(u16, u16)> = row["fc"]
                .as_array()
                .unwrap()
                .iter()
                .map(|c| parse_cell(c).unwrap())
                .collect();
            expect.sort();
            let got = fc_to_sorted(&env.extended_final_component(bn, sup), n);
            assert_eq!(got, expect, "{tag}: extended fc of ({bn:?},{sup:?})");
            n_ext += 1;
        }
    }
    println!(
        "fixture (c) PASS: {} boards, {n_plain} plain + {n_ext} extended final components",
        lines.len()
    );
}

// -- (d) replay decisions -----------------------------------------------------

#[test]
fn fixture_d_replay_decisions() {
    let lines = read_jsonl_gz("decisions.jsonl.gz");
    assert!(!lines.is_empty());
    let mut cache = BoardCache::new();
    let (mut n_dec, mut n_labels, mut n_rejected, mut n_unreach) = (0, 0, 0, 0);
    for line in &lines {
        let id = line["id"].as_str().unwrap();
        let board = cache.get(line);
        let env = SubgoalEnv::new(board);
        let item = parse_replay_decision(line).unwrap_or_else(|e| panic!("{id}: {e}"));
        let labels = replay_decision(&env, &item).unwrap_or_else(|e| panic!("{id}: {e}"));
        let py = line["python_labels"].as_array().unwrap();
        assert_eq!(labels.len(), py.len(), "{id}: label count");
        for (i, (rs, pl)) in labels.iter().zip(py.iter()).enumerate() {
            assert_eq!(rs.ctg, pl["ctg"].as_i64(), "{id} cand {i}: ctg");
            assert_eq!(
                rs.rejected,
                pl["rejected"].as_bool().unwrap(),
                "{id} cand {i}: rejected"
            );
            n_labels += 1;
            if rs.rejected {
                n_rejected += 1;
            } else if rs.ctg.is_none() {
                n_unreach += 1;
            }
        }
        n_dec += 1;
    }
    println!(
        "fixture (d) PASS: {n_dec} decisions, {n_labels} per-candidate labels \
         ({n_rejected} rejected, {n_unreach} unsolved), zero diffs"
    );
}

// -- (e) full rollouts --------------------------------------------------------

/// Canonical form of one record (serde_json Value objects are BTreeMap-backed,
/// so `to_string` is key-sorted and comparison is field-order-proof).
fn canon(v: &Value) -> String {
    v.to_string()
}

/// Full-scale replay sweep over an uncommitted dump (gate 3, Agent E2's
/// battery). Point RUST_DATAGEN_BACKWARD_DUMP at a `dump_decisions.py
/// --task backward` output (plain jsonl) and run:
///   RUST_DATAGEN_BACKWARD_DUMP=... cargo test --release --test \
///     backward_fixtures -- --ignored replay_dump --nocapture
#[test]
#[ignore]
fn replay_dump_full() {
    let path = std::env::var("RUST_DATAGEN_BACKWARD_DUMP")
        .expect("set RUST_DATAGEN_BACKWARD_DUMP to a backward decisions dump");
    let text = std::fs::read_to_string(&path).unwrap();
    let mut cache = BoardCache::new();
    let (mut n_dec, mut n_labels, mut n_diff) = (0usize, 0usize, 0usize);
    for raw in text.lines().filter(|l| !l.trim().is_empty()) {
        let line: Value = serde_json::from_str(raw).unwrap();
        let id = line["id"].as_str().unwrap_or("?").to_string();
        let board = cache.get(&line);
        let env = SubgoalEnv::new(board);
        let item = parse_replay_decision(&line).unwrap_or_else(|e| panic!("{id}: {e}"));
        let labels = replay_decision(&env, &item).unwrap_or_else(|e| panic!("{id}: {e}"));
        let py = line["python_labels"].as_array().unwrap();
        assert_eq!(labels.len(), py.len(), "{id}: label count");
        for (i, (rs, pl)) in labels.iter().zip(py.iter()).enumerate() {
            n_labels += 1;
            if rs.ctg != pl["ctg"].as_i64() || rs.rejected != pl["rejected"].as_bool().unwrap() {
                n_diff += 1;
                eprintln!(
                    "DIFF {id} cand {i}: rust=({:?},{}) py=({:?},{})",
                    rs.ctg, rs.rejected, pl["ctg"], pl["rejected"]
                );
            }
        }
        n_dec += 1;
    }
    println!("replay_dump_full: {n_dec} decisions, {n_labels} labels, {n_diff} diffs");
    assert_eq!(n_diff, 0, "label diffs found");
}

/// Rough single-thread rollout throughput at 16×16 (--release; task-brief
/// perf note). Reuses the committed g16r4 rollout fixtures.
///   cargo test --release --test backward_fixtures -- --ignored bench --nocapture
#[test]
#[ignore]
fn bench_rollout_rate_16x16() {
    let lines = read_jsonl_gz("rollouts.jsonl.gz");
    let mut cache = BoardCache::new();
    let mut jobs = Vec::new();
    for line in &lines {
        if line["tag"].as_str().unwrap() != "g16r4" {
            continue;
        }
        let board = cache.get(line).clone();
        let state = parse_state(&line["state"]).unwrap();
        let env_id = line["board"]["env_id"].as_i64().unwrap();
        jobs.push((board, state, env_id));
    }
    let solver = AStar { max_iters: 4000, max_frontier: 40_000, ..AStar::default() };
    let reps = 50usize;
    let t0 = std::time::Instant::now();
    let mut n_rec = 0usize;
    for _ in 0..reps {
        for (board, state, env_id) in &jobs {
            let env = SubgoalEnv::new(board);
            let res = rollout_traced(&env, state, &solver, *env_id, Some(14), None, None);
            n_rec += res.records.len();
        }
    }
    let dt = t0.elapsed().as_secs_f64();
    let n = reps * jobs.len();
    println!(
        "bench: {n} rollouts ({n_rec} records) in {dt:.2}s = {:.1} rollouts/s single-thread (fresh SubgoalEnv per rollout)",
        n as f64 / dt
    );
}

/// (bn, sp, helper pos, helper color) key of a record's candidate, for trace
/// score lookup.
type RecCandKey = ((u16, u16), (u16, u16), (u16, u16), String);

fn rec_cand_key(r: &Value) -> RecCandKey {
    (
        parse_cell(&r["cand_bottleneck"]).unwrap(),
        parse_cell(&r["cand_support"]).unwrap(),
        parse_cell(&r["cand_helper"][0]).unwrap(),
        r["cand_helper"][1].as_str().unwrap().to_string(),
    )
}

#[test]
fn fixture_e_full_rollouts() {
    let lines = read_jsonl_gz("rollouts.jsonl.gz");
    assert_eq!(lines.len(), 12, "expected 12 committed rollouts");
    let mut cache = BoardCache::new();
    let (mut n_dec_exact, mut n_dec_multiset, mut n_dec_tie, mut n_records, mut n_forked) =
        (0usize, 0usize, 0usize, 0usize, 0usize);
    let mut forked: Vec<String> = Vec::new();
    for line in &lines {
        let tag = line["tag"].as_str().unwrap();
        let env_id = line["board"]["env_id"].as_i64().unwrap();
        let board = cache.get(line);
        let env = SubgoalEnv::new(board);
        let state = parse_state(&line["state"]).unwrap();
        let solver = AStar {
            max_iters: line["max_iters"].as_u64().unwrap(),
            max_frontier: line["max_frontier"].as_u64().unwrap() as usize,
            ..AStar::default()
        };
        let mc = line["max_candidates"].as_u64().unwrap() as usize;

        let mut traces = Vec::new();
        let res = rollout_traced(&env, &state, &solver, env_id, Some(mc), None, Some(&mut traces));
        assert_eq!(res.status, RolloutStatus::Ok, "{tag}/e{env_id}: rollout status");
        let rust_recs: Vec<Value> = res
            .records
            .iter()
            .map(|r| serde_json::to_value(r).unwrap())
            .collect();
        // Total counts may differ legitimately: a truncation-boundary score
        // tie can swap kept candidates, and swapped candidates need not all
        // produce labels. Validation is per depth below.
        let py_recs = line["records"].as_array().unwrap();

        // Group by depth (records at one decision share a depth; depth only
        // increments on decisions).
        let group = |recs: &[Value]| -> HashMap<i64, Vec<Value>> {
            let mut m: HashMap<i64, Vec<Value>> = HashMap::new();
            for r in recs {
                m.entry(r["depth"].as_i64().unwrap()).or_default().push(r.clone());
            }
            m
        };
        let py_by_depth = group(py_recs);
        let rs_by_depth = group(&rust_recs);
        let mut depths: Vec<i64> = py_by_depth
            .keys()
            .chain(rs_by_depth.keys())
            .copied()
            .collect();
        depths.sort();
        depths.dedup();
        let mut prev_d: Option<i64> = None;
        for d in depths {
            // Decision-point identity: all records at one depth share the
            // seg_*/ctx_* fields, which fingerprint the partial plan being
            // decided. A mismatch (or a depth present on one side only)
            // means the trajectories FORKED at the previous decision — legal
            // exactly when that decision had several distinct optimal
            // candidates (the advance picks the FIRST best in candidate
            // order, which is Python-set order, DESIGN §5.11).
            let plan_fp = |r: &Value| -> String {
                format!(
                    "{}|{}|{}|{}|{}|{}",
                    r["seg_start"], r["seg_end"], r["seg_support"],
                    r["ctx_bottlenecks"], r["ctx_supports"], r["ctx_open_endpoints"]
                )
            };
            let aligned = match (py_by_depth.get(&d), rs_by_depth.get(&d)) {
                (Some(py), Some(rs)) => plan_fp(&py[0]) == plan_fp(&rs[0]),
                _ => false,
            };
            if !aligned {
                let pd = prev_d.unwrap_or_else(|| {
                    panic!("{tag}/e{env_id} depth {d}: misaligned at the first decision")
                });
                let opt_cands = |recs: &[Value]| -> Vec<String> {
                    let mut v: Vec<String> = recs
                        .iter()
                        .filter(|r| r["is_optimal"] == Value::Bool(true))
                        .map(|r| format!("{:?}", rec_cand_key(r)))
                        .collect();
                    v.sort();
                    v.dedup();
                    v
                };
                let py_opt = opt_cands(&py_by_depth[&pd]);
                let rs_opt = opt_cands(&rs_by_depth[&pd]);
                let mut union = py_opt.clone();
                union.extend(rs_opt.iter().cloned());
                union.sort();
                union.dedup();
                assert!(
                    !py_opt.is_empty() && !rs_opt.is_empty() && union.len() >= 2,
                    "{tag}/e{env_id} depth {d}: fork without an optimal tie at depth {pd}"
                );
                n_forked += 1;
                forked.push(format!("{tag}/e{env_id}@d{d}"));
                break;
            }
            let py = &py_by_depth[&d];
            let rs = &rs_by_depth[&d];
            prev_d = Some(d);
            n_records += py.len();
            let py_c: Vec<String> = py.iter().map(canon).collect();
            let rs_c: Vec<String> = rs.iter().map(canon).collect();
            if py_c == rs_c {
                n_dec_exact += 1;
                continue;
            }
            let mut pys = py_c.clone();
            let mut rss = rs_c.clone();
            pys.sort();
            rss.sort();
            if pys == rss {
                n_dec_multiset += 1;
                continue;
            }
            // Multiset differs: must be the documented truncation-tie class
            // (stable sort at equal scores keeps a different candidate SET
            // when the score tie straddles the max_candidates boundary —
            // candidate pre-sort order is Python-set order, DESIGN §5.11).
            // Swapped-in/out candidates need not all label, so record counts
            // may differ; the binding invariants are:
            //  - every divergent record's candidate was proposed with score
            //    EXACTLY equal to the truncation boundary score, and
            //  - both sides agree on the minimum cost_to_go (the label that
            //    defines is_optimal and the advance).
            let diff = |a: &[String], b: &[String]| -> Vec<String> {
                let mut b_left: Vec<&String> = b.iter().collect();
                a.iter()
                    .filter(|x| {
                        if let Some(i) = b_left.iter().position(|y| **y == **x) {
                            b_left.remove(i);
                            false
                        } else {
                            true
                        }
                    })
                    .cloned()
                    .collect()
            };
            let py_only = diff(&pys, &rss);
            let rs_only = diff(&rss, &pys);
            let min_ctg = |recs: &[Value]| {
                recs.iter().map(|r| r["cost_to_go"].as_i64().unwrap()).min().unwrap()
            };
            assert_eq!(
                min_ctg(py),
                min_ctg(rs),
                "{tag}/e{env_id} depth {d}: best cost_to_go differs — label divergence, not the tie class"
            );
            let trace = traces
                .iter()
                .find(|t| t.depth == d)
                .unwrap_or_else(|| panic!("{tag}/e{env_id} depth {d}: no trace"));
            assert!(
                trace.all_candidates.len() > mc && rs.len() <= mc,
                "{tag}/e{env_id} depth {d}: truncation not active — divergence not the tie class"
            );
            let boundary_score = trace.all_candidates[mc - 1].score;
            for s in py_only.iter().chain(rs_only.iter()) {
                let r: Value = serde_json::from_str(s).unwrap();
                let key = rec_cand_key(&r);
                let cand = trace
                    .all_candidates
                    .iter()
                    .find(|c| {
                        c.subgoal.bottleneck.pos == key.0
                            && c.subgoal.support.pos == key.1
                            && c.subgoal.helper.pos == key.2
                            && c.subgoal.helper.color_str() == key.3
                    })
                    .unwrap_or_else(|| {
                        panic!("{tag}/e{env_id} depth {d}: divergent record's candidate not proposed")
                    });
                assert_eq!(
                    cand.score, boundary_score,
                    "{tag}/e{env_id} depth {d}: divergent candidate score != truncation boundary"
                );
            }
            n_dec_tie += 1;
        }
    }
    println!(
        "fixture (e) PASS: 12 rollouts, {} aligned decisions ({n_dec_exact} exact-order, \
         {n_dec_multiset} multiset-only, {n_dec_tie} truncation-tie validated), \
         {n_records} records; {n_forked} rollouts forked on an optimal tie \
         (validated): {forked:?}",
        n_dec_exact + n_dec_multiset + n_dec_tie
    );
}
